[workspace]
members = ["projects/*"]
default-members = [
    "projects/waifu-diffuser-types",
    "projects/waifu-diffuser-server"
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
