[package]
name = "waifu-diffuser-types"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "Types definitions for waifu-diffuser"
repository = "https://github.com/oovm/waifu-diffuser"
documentation = "https://docs.rs/waifu-diffuser-types"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
uuid = { version = "1.3.0", features = ["serde", "v7"] }
serde = { version = "1.0.130", features = ["derive"] }
#diffusers = "0.2.1"
serde_json5 = "0.1.0"
walkdir = "2.3.2"
diffuser-scheduler = "0.0.0"

[dependencies.sevenz-rust]
version = "0.2.0"
git = "https://github.com/dyz1990/sevenz-rust.git"
branch = "7z_edit"
features = ["compress"]
#serde-aux = "4.1.2"

[dependencies.diagnostic-quick]
version = "0.4.0"
features = ["walkdir", "json5"]

[dev-dependencies]

[features]
default = []
